### ISSUE TITLE
Issues i've found

### ISSUE THREAD

**Issue by yatt-ze** [TheScrawl/ncpyrpg#3]
- Lenny face ascii art doesnt work due to how the characters are handled. Not sure how to fix

- Many emoji do not work, due to being more than one character large

- due to use of eval() when i made map objects, could potentially lead to games being used for malicious purposes - though unlikely. I may redo how the map objects work in future to get rid of this issue, but at present i cbf

**Comment by TheScrawl** [comment]
These are known issues that i cant be bothered fixing
